### PR TITLE
Query.prototype.segment accepts an input query.

### PR DESCRIPTION
**Pull request by dan-kez**
In regards to issue #38

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Can you show me a code use case so I can figure this out a bit more.

**Comment by dan-kez** [comment]
A bit of a forced example below but it gets the idea across. 

``` js
function makeGetQuery() {
    var cypher = new Query().match('(n:Label1)')

   return cypher;
}

function makeSetLabelQuery(label) {
     var cypher = new Query();
     cypher.segment(makeGetQuery())
                .set('n:{label}', {label: label});
     return cypher;
}
```

**Comment by Yomguithereal** [comment]
Hum... Why not?

**Comment by Yomguithereal** [comment]
v0.10.0 published.

**Pull request merged**
